baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://ajua.github.io" # the base hostname & protocol for your site
title: "阿爪的筆記本 AJus's notebook"
author: "阿爪"
author_en: "AJua"

excerpt_separator: <!--more-->

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
